name: Build example site

on:
  pull_request:
    branches:
      - master
      - exampleSite

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: exampleSite

      - name: Get Theme
        run: |
          git submodule update --init --recursive
          cd themes/harbor
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
          cd ../..

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --buildDrafts --gc --minify
